package com.unewexp.superblockly.enums

enum class BlockType{
    OPERAND,
    SET_VARIABLE_VALUE,
    START,
    VARIABLE_DECLARATION,
    INT_LITERAL,
    STRING_LITERAL,
    BOOLEAN_LITERAL,
    VARIABLE_REFERENCE,
    STRING_CONCAT,
    STRING_APPEND,
    PRINT_BLOCK,
    COMPARE_NUMBERS_BLOCK,
    BOOLEAN_LOGIC_BLOCK,
    NOT_BLOCK,
    IF_BLOCK,
    ELSE_BLOCK,
    IF_ELSE_BLOCK
}